=== ddvloayza/jericho-extractor/schemas/route_table_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "RouteTable",
  "type": "object",
  "required": ["resource_type", "resource_id", "account_id", "account_name", "region"],
  "properties": {
    "resource_type":           { "type": "string", "const": "aws::ec2::route_table" },
    "resource_id":             { "type": "string" },
    "account_id":              { "type": "string" },
    "account_name":            { "type": "string" },
    "region":                  { "type": "string" },
    "vpc_id":                  { "type": "string" },
    "is_main":                 { "type": "boolean" },
    "associated_subnet_ids":   { "type": "array", "items": { "type": "string" } },
    "routes":                  { "type": "array" },
    "tags":                    { "type": "object" },
    "relationships":           { "type": "array" },
    "collected_at":            { "type": "string", "format": "date-time" }
  }
}

=== ddvloayza/jericho-extractor/output/Interchange-Dev/route_tables.json
[
  {
    "resource_type": "aws::ec2::route_table",
    "resource_id": "rtb-0d2f6157175f4ae5e",
    "account_id": "861276092327",
    "account_name": "Interchange-Dev",
    "region": "eu-south-2",
    "vpc_id": "vpc-0101d2c447b67e9db",
    "is_main": false,
    "associated_subnet_ids": [
      "subnet-03cb8477fb39f639e",
      "subnet-0b02ad525f046501b"
    ],
    "routes": [
      {
        "destination_cidr": "172.8.3.32/32",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "",
        "nat_gateway_id": "",
        "transit_gateway_id": "tgw-042a72cb246bebf1e",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "10.0.3.0/24",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "",
        "nat_gateway_id": "",
        "transit_gateway_id": "tgw-042a72cb246bebf1e",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "10.0.4.0/24",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "",
        "nat_gateway_id": "",
        "transit_gateway_id": "tgw-042a72cb246bebf1e",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "100.0.4.0/24",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "",
        "nat_gateway_id": "",
        "transit_gateway_id": "tgw-042a72cb246bebf1e",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "172.5.0.0/16",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "",
        "nat_gateway_id": "",
        "transit_gateway_id": "tgw-042a72cb246bebf1e",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "172.8.0.0/16",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "",
        "nat_gateway_id": "",
        "transit_gateway_id": "tgw-042a72cb246bebf1e",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "10.14.0.0/16",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "local",
        "nat_gateway_id": "",
        "transit_gateway_id": "",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRouteTable"
      },
      {
        "destination_cidr": "10.18.0.0/16",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "",
        "nat_gateway_id": "",
        "transit_gateway_id": "tgw-042a72cb246bebf1e",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "0.0.0.0/0",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "",
        "nat_gateway_id": "nat-0c77344696fe6a32a",
        "transit_gateway_id": "",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "pl-64a5400d",
        "gateway_id": "vpce-0b04c1a531f936e19",
        "nat_gateway_id": "",
        "transit_gateway_id": "",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "pl-68a74201",
        "gateway_id": "vpce-05f9b263127d26370",
        "nat_gateway_id": "",
        "transit_gateway_id": "",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      }
    ],
    "tags": {
      "apid": "itx",
      "assetid": "0004",
      "env": "dev",
      "Name": "itl-0004-itx-dev-rt-private-02",
      "coid": "itl"
    },
    "relationships": [
      {
        "resource_type": "aws::ec2::vpc",
        "resource_id": "vpc-0101d2c447b67e9db",
        "relation": "belongs_to_vpc"
      },
      {
        "resource_type": "aws::ec2::subnet",
        "resource_id": "subnet-03cb8477fb39f639e",
        "relation": "associated_with_subnet"
      },
      {
        "resource_type": "aws::ec2::subnet",
        "resource_id": "subnet-0b02ad525f046501b",
        "relation": "associated_with_subnet"
      }
    ],
    "collected_at": "2026-08-15T07:45:14.404317+00:00"
  },
  {
    "resource_type": "aws::ec2::route_table",
    "resource_id": "rtb-0b4d0b1fa0dcee3a0",
    "account_id": "861276092327",
    "account_name": "Interchange-Dev",
    "region": "eu-south-2",
    "vpc_id": "vpc-0101d2c447b67e9db",
    "is_main": false,
    "associated_subnet_ids": [
      "subnet-0b7a74c150cca70e7",
      "subnet-05828a4204425c59b"
    ],
    "routes": [
      {
        "destination_cidr": "10.14.0.0/16",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "local",
        "nat_gateway_id": "",
        "transit_gateway_id": "",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRouteTable"
      },
      {
        "destination_cidr": "0.0.0.0/0",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "igw-049a6140343c8f6d2",
        "nat_gateway_id": "",
        "transit_gateway_id": "",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "pl-64a5400d",
        "gateway_id": "vpce-0b04c1a531f936e19",
        "nat_gateway_id": "",
        "transit_gateway_id": "",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "pl-68a74201",
        "gateway_id": "vpce-05f9b263127d26370",
        "nat_gateway_id": "",
        "transit_gateway_id": "",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      }
    ],
    "tags": {
      "Name": "itl-0004-itx-dev-rt-public-02",
      "env": "dev",
      "apid": "itx",
      "assetid": "0004",
      "coid": "itl"
    },
    "relationships": [
      {
        "resource_type": "aws::ec2::vpc",
        "resource_id": "vpc-0101d2c447b67e9db",
        "relation": "belongs_to_vpc"
      },
      {
        "resource_type": "aws::ec2::subnet",
        "resource_id": "subnet-0b7a74c150cca70e7",
        "relation": "associated_with_subnet"
      },
      {
        "resource_type": "aws::ec2::subnet",
        "resource_id": "subnet-05828a4204425c59b",
        "relation": "associated_with_subnet"
      }
    ],
    "collected_at": "2026-08-15T07:45:14.404347+00:00"
  },
  {
    "resource_type": "aws::ec2::route_table",
    "resource_id": "rtb-07ad7f49cb04604ad",
    "account_id": "861276092327",
    "account_name": "Interchange-Dev",
    "region": "eu-south-2",
    "vpc_id": "vpc-0101d2c447b67e9db",
    "is_main": false,
    "associated_subnet_ids": [
      "subnet-09162acc62b24d7cb",
      "subnet-05dae71c2f90dc501"
    ],
    "routes": [
      {
        "destination_cidr": "10.0.3.100/32",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "",
        "nat_gateway_id": "",
        "transit_gateway_id": "tgw-042a72cb246bebf1e",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "172.2.0.0/16",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "",
        "nat_gateway_id": "",
        "transit_gateway_id": "tgw-042a72cb246bebf1e",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
        "destination_cidr": "172.5.0.0/16",
        "destination_ipv6_cidr": "",
        "destination_prefix_list_id": "",
        "gateway_id": "",
        "nat_gateway_id": "",
        "transit_gateway_id": "tgw-042a72cb246bebf1e",
        "vpc_peering_connection_id": "",
        "network_interface_id": "",
        "instance_id": "",
        "state": "active",
        "origin": "CreateRoute"
      },
      {
