=== ddvloayza/jericho-extractor/schemas/vpc_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "VPC",
  "type": "object",
  "required": ["resource_type", "resource_id", "account_id", "account_name", "region"],
  "properties": {
    "resource_type":            { "type": "string", "const": "aws::ec2::vpc" },
    "resource_id":              { "type": "string" },
    "account_id":               { "type": "string" },
    "account_name":             { "type": "string" },
    "region":                   { "type": "string" },
    "cidr_block":               { "type": "string" },
    "cidr_block_associations":  { "type": "array", "items": { "type": "string" } },
    "ipv6_cidr_blocks":         { "type": "array", "items": { "type": "string" } },
    "state":                    { "type": "string" },
    "is_default":               { "type": "boolean" },
    "dhcp_options_id":          { "type": "string" },
    "instance_tenancy":         { "type": "string" },
    "tags":                     { "type": "object" },
    "relationships":            { "type": "array" },
    "collected_at":             { "type": "string", "format": "date-time" }
  }
}

=== ddvloayza/jericho-extractor/output/Analytics-Dev/vpcs.json
[
  {
    "resource_type": "aws::ec2::vpc",
    "resource_id": "vpc-0f4a2881864e2f145",
    "account_id": "221082197632",
    "account_name": "Analytics-Dev",
    "region": "eu-south-2",
    "cidr_block": "172.31.0.0/16",
    "cidr_block_associations": [
      "172.31.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "state": "available",
    "is_default": true,
    "dhcp_options_id": "dopt-0f626424cf4e9cd11",
    "instance_tenancy": "default",
    "tags": {},
    "relationships": [
      {
        "resource_type": "aws::ec2::dhcp_options",
        "resource_id": "dopt-0f626424cf4e9cd11",
        "relation": "uses_dhcp"
      }
    ],
    "collected_at": "2026-07-12T19:45:41.385348+00:00"
  },
  {
    "resource_type": "aws::ec2::vpc",
    "resource_id": "vpc-092dc05179287e08a",
    "account_id": "221082197632",
    "account_name": "Analytics-Dev",
    "region": "eu-south-2",
    "cidr_block": "10.16.0.0/16",
    "cidr_block_associations": [
      "10.16.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "state": "available",
    "is_default": false,
    "dhcp_options_id": "dopt-0f626424cf4e9cd11",
    "instance_tenancy": "default",
    "tags": {
      "assetid": "0005",
      "coid": "itl",
      "Name": "itl-0005-ana-dev-vpc-02",
      "apid": "ana",
      "env": "dev"
    },
    "relationships": [
      {
        "resource_type": "aws::ec2::dhcp_options",
        "resource_id": "dopt-0f626424cf4e9cd11",
        "relation": "uses_dhcp"
      }
    ],
    "collected_at": "2026-07-12T19:45:41.385360+00:00"
  }
]

=== ddvloayza/jericho-extractor/output/Portal-Dev/vpcs.json
[
  {
    "resource_type": "aws::ec2::vpc",
    "resource_id": "vpc-0fbd191d169cc9efb",
    "account_id": "891376942769",
    "account_name": "Portal-Dev",
    "region": "eu-south-2",
    "cidr_block": "10.12.0.0/16",
    "cidr_block_associations": [
      "10.12.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "state": "available",
    "is_default": false,
    "dhcp_options_id": "dopt-0ef5151411f7dc49f",
    "instance_tenancy": "default",
    "tags": {
      "env": "dev",
      "assetid": "0003",
      "coid": "itl",
      "Name": "itl-0003-portal-dev-vpc-02",
      "apid": "portal"
    },
    "relationships": [
      {
        "resource_type": "aws::ec2::dhcp_options",
        "resource_id": "dopt-0ef5151411f7dc49f",
        "relation": "uses_dhcp"
      }
    ],
    "collected_at": "2026-08-15T07:50:17.516046+00:00"
  },
  {
    "resource_type": "aws::ec2::vpc",
    "resource_id": "vpc-086471f116a4c4c20",
    "account_id": "891376942769",
    "account_name": "Portal-Dev",
    "region": "eu-south-2",
    "cidr_block": "172.31.0.0/16",
    "cidr_block_associations": [
      "172.31.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "state": "available",
    "is_default": true,
    "dhcp_options_id": "dopt-0ef5151411f7dc49f",
    "instance_tenancy": "default",
    "tags": {},
    "relationships": [
      {
        "resource_type": "aws::ec2::dhcp_options",
        "resource_id": "dopt-0ef5151411f7dc49f",
        "relation": "uses_dhcp"
      }
    ],
    "collected_at": "2026-08-15T07:50:17.516073+00:00"
  }
]

=== ddvloayza/jericho-extractor/output/Interchange-Dev/vpcs.json
[
  {
    "resource_type": "aws::ec2::vpc",
    "resource_id": "vpc-029134477d2a41610",
    "account_id": "861276092327",
    "account_name": "Interchange-Dev",
    "region": "eu-south-2",
    "cidr_block": "172.31.0.0/16",
    "cidr_block_associations": [
      "172.31.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "state": "available",
    "is_default": true,
    "dhcp_options_id": "dopt-0a3064911df7dfbb9",
    "instance_tenancy": "default",
    "tags": {},
    "relationships": [
      {
        "resource_type": "aws::ec2::dhcp_options",
        "resource_id": "dopt-0a3064911df7dfbb9",
        "relation": "uses_dhcp"
      }
    ],
    "collected_at": "2026-08-15T07:45:13.840225+00:00"
  },
  {
    "resource_type": "aws::ec2::vpc",
    "resource_id": "vpc-0101d2c447b67e9db",
    "account_id": "861276092327",
    "account_name": "Interchange-Dev",
    "region": "eu-south-2",
    "cidr_block": "10.14.0.0/16",
    "cidr_block_associations": [
      "10.14.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "state": "available",
    "is_default": false,
    "dhcp_options_id": "dopt-0a3064911df7dfbb9",
    "instance_tenancy": "default",
    "tags": {
      "Name": "itl-0004-itx-dev-vpc-02",
      "coid": "itl",
      "apid": "itx",
      "env": "dev",
      "assetid": "0004"
    },
    "relationships": [
      {
        "resource_type": "aws::ec2::dhcp_options",
        "resource_id": "dopt-0a3064911df7dfbb9",
        "relation": "uses_dhcp"
      }
    ],
    "collected_at": "2026-08-15T07:45:13.840248+00:00"
  }
]
